version: '3'

services:
  # Summarization Service API
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - GROKX_API_KEY=${GROKX_API_KEY}
      - GROKX_API_URL=https://api.x.ai/v1/chat/completions
    depends_on:
      - redis
    restart: unless-stopped
  
  # Redis for status tracking
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: